DROP TABLE IF EXISTS step_memos;

DROP TABLE IF EXISTS record_steps;

DROP TYPE IF EXISTS STEP_TYPE;

DROP TABLE IF EXISTS snapshot_memos;

DROP TABLE IF EXISTS record_snapshots;

DROP TABLE IF EXISTS records;